name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.11.0
      with:
        php-version: '8.0'
        coverage: xdebug
        extensions: inotify
        tools: composer:v2, phpunit, vimeo/psalm, php-cs-fixer
      env:
        fail-fast: true
